include:
  - configs/openai.yml
  - configs/anthropic.yml
  - configs/model-groups.yml
  - configs/model-routing.yml

general_settings:
  master_key: os.environ/MASTER_KEY
  forward_openai_org_id: true

# guardrails:
#   - guardrail_name: "presidio-pre-guard"
#     litellm_params:
#       guardrail: presidio # supported values: "aporia", "bedrock", "lakera", "presidio"
#       mode: "pre_call"
#       output_parse_pii: True

litellm_settings:
  drop_params: true
